{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.configmap.annotations }}
  annotations: 
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.podAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configmap.annotations "context" $) | nindent 8 }}
    {{- end }}
  {{- end }}
data:
{{- include "common.tplvalues.render" ( dict "value" .Values.configmap.data "context" $) | nindent 2 }}
{{- end }}